-- First drop the tables if they exist
DROP TABLE IF EXISTS notes;
DROP TABLE IF EXISTS folders;

CREATE TABLE folders (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    folder_name TEXT NOT NULL
);

CREATE TABLE notes (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    note_name TEXT NOT NULL,
    modified TIMESTAMP NOT NULL DEFAULT now(),
    folder_id INTEGER REFERENCES folders(id) NOT NULL,
    note_content TEXT NOT NULL
);